package org.offdic

/**
 * Part-of-speech code tables, ported verbatim from the original `FDWordPartOfSpeech`.
 *
 * The database stores a numeric POS code per detail. An English detail renders
 * "noun · اسم" (English label plus its Persian equivalent) and a Persian detail renders its own
 * label, exactly as the original suggestion/result lists did. Codes outside a table return an
 * empty string; callers drop blanks.
 */
object PartOfSpeech {
    fun getEnglish(posId: Int): String = when (posId) {
        1 -> "noun"
        2 -> "plural"
        3 -> "noun phrase"
        4 -> "verb - use participle"
        5 -> "verb - transitive"
        6 -> "verb - intransitive"
        7 -> "adjective"
        8 -> "adverb"
        9 -> "conjunction"
        10 -> "preposition"
        11 -> "interjection"
        12 -> "pronoun"
        13 -> "definite article"
        14 -> "indefinite article"
        15 -> "nominative"
        16 -> "prefix"
        17 -> "suffix"
        18 -> "idiom"
        19 -> "collocation"
        20 -> "phrasal verb"
        21 -> "auxiliary verb"
        22 -> "determiner"
        23 -> "predeterminer"
        24 -> "abbreviation"
        25 -> "slang"
        26 -> "idiomatic phrase"
        27 -> "acronym"
        28 -> "symbol"
        29 -> "verb phrase"
        30 -> "phrase"
        31 -> "singular"
        32 -> "exclamation"
        33 -> "contraction"
        34 -> "proverb"
        else -> ""
    }

    fun getPersian(posId: Int): String = when (posId) {
        1 -> "اسم"
        2 -> "صفت"
        3 -> "قید"
        4 -> "فعل لازم"
        5 -> "فعل متعدی"
        6 -> "پسوند"
        7 -> "سازه\u200cی پیوندی"
        8 -> "اسم خاص"
        9 -> "اسم مشتق"
        10 -> "فعل مشتق"
        11 -> "نام آوا"
        12 -> "حرف اضافه"
        13 -> "پیشوند"
        14 -> "اسم عام"
        15 -> "شبه\u200cجمله"
        16 -> "ضمیر"
        17 -> "فعل پیشوندی"
        18 -> "فعل مرکب"
        19 -> "صفت مرکب اتباعی"
        20 -> "حرف ندا"
        21 -> "اسم جمع"
        22 -> "حرف ربط"
        23 -> "صوت"
        24 -> "مخفف"
        25 -> "سرواژه"
        26 -> "نماد"
        27 -> "جمله"
        28 -> "ضرب\u200cالمثل"
        29 -> "اصطلاح"
        30 -> "عبارت"
        31 -> "فعل کمکی"
        else -> ""
    }

    fun findEnglishEquivalentInPersian(posId: Int): String = when (posId) {
        1 -> "اسم"
        2 -> "جمع"
        3 -> "عبارت اسمی"
        4 -> "صفت فعلی"
        5 -> "فعل متعدی"
        6 -> "فعل لازم"
        7 -> "صفت"
        8 -> "قید"
        9 -> "حرف ربط"
        10 -> "حرف اضافه"
        11 -> "صوت"
        12 -> "ضمیر"
        13 -> "حرف معرفه، حرف تعریف"
        14 -> "حرف نکره"
        15 -> "نهاد"
        16 -> "پیشوند"
        17 -> "پسوند"
        18 -> "اصطلاح"
        19 -> "هم\u200cنشین"
        20 -> "فعل عبارتی"
        21 -> "فعل کمکی"
        22 -> "معرفه\u200cی اسم"
        23 -> "پیش\u200c معرفه"
        24 -> "مخفف"
        25 -> "عامیانه"
        26 -> "عبارت اصطلاحی"
        27 -> "سرواژه"
        28 -> "نماد"
        29 -> "عبارت فعلی"
        30 -> "عبارت"
        31 -> "اسم مفرد"
        32 -> "حرف ندا"
        33 -> "شکل اختصار"
        34 -> "ضرب\u200cالمثل"
        else -> ""
    }
}
