#!/usr/bin/env python3
"""Reproducible static inventory; not a semantic review or proof of feature parity."""
from pathlib import Path
import re
import sqlite3
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
A = '{http://schemas.android.com/apk/res/android}'
APP = '{http://schemas.android.com/apk/res-auto}'
java = sorted((ROOT / 'sourcecode').rglob('*.java'))
smali = sorted((ROOT / 'dict').rglob('*.smali'))
rows = ['# Original source inventory', '',
        'Generated by `python3 tools/audit_original.py`. This is a full-tree static inventory, not a claim that every method was manually reviewed.', '',
        f'- Java files: {len(java)}', f'- Smali files: {len(smali)}',
        f'- Resource files: {sum(p.is_file() for p in (ROOT / "res").rglob("*"))}', '',
        '## Navigation destinations', '', '| Graph | ID | Class |', '|---|---|---|']
for graph in sorted((ROOT / 'res/navigation').glob('*.xml')):
    for e in ET.parse(graph).getroot():
        if e.tag in ('fragment', 'dialog', 'activity'):
            rows.append(f'| {graph.name} | {e.get(A+"id", "")} | {e.get(A+"name", "")} |')
rows += ['', '## Original app components', '']
manifest = ET.parse(ROOT / 'AndroidManifest.xml')
for e in manifest.getroot().find('application'):
    if e.tag in ('activity', 'service', 'provider', 'receiver') and e.get(A+'name', '').startswith('fast.dic'):
        rows.append(f'- `{e.tag}`: `{e.get(A+"name")}`')
rows += ['', '## Source groups', '', '| Directory | Java files |', '|---|---:|']
counts = {}
for p in java:
    group = str(p.parent.relative_to(ROOT / 'sourcecode'))
    counts[group] = counts.get(group, 0) + 1
rows += [f'| `{k}` | {v} |' for k,v in sorted(counts.items())]
rows += ['', '## Monetization / entitlement reference locations', '',
         'Search hits are audit candidates, not necessarily feature gates. Generated synthetic classes are omitted from this list. None of these original source directories is included in the new app source set.', '']
pattern = re.compile(r'\b(?:isPro|isPremium|hasSubscription|isSubscribed|ProPlan|proPlan|BillingClient|FDAds|Appodeal)\b', re.I)
for p in java:
    if '$' in p.name or any(x in p.name for x in ('_Factory', '_Members', 'Hilt', '_Generated')): continue
    hits = [str(i) for i,line in enumerate(p.read_text(errors='replace').splitlines(), 1) if not line.startswith('@Metadata') and pattern.search(line)]
    if hits: rows.append(f'- `{p.relative_to(ROOT)}`: lines {", ".join(hits)}')
rows += ['', '## Database schema / sample counts', '', '| Table | Rows | Columns |', '|---|---:|---|']
with sqlite3.connect(f'file:{ROOT / "dbsample/sample.sqlite"}?mode=ro', uri=True) as db:
    for (table,) in db.execute("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name"):
        columns = ', '.join(r[1] for r in db.execute(f'PRAGMA table_info("{table}")'))
        count = db.execute(f'SELECT COUNT(*) FROM "{table}"').fetchone()[0]
        rows.append(f'| `{table}` | {count} | {columns} |')
rows += ['', '## Decompiled methods requiring reconstruction', '', 'Methods with a decompiler failure marker need comparison against Smali before claiming equivalent behavior.', '']
for p in java:
    hits = [str(i) for i,line in enumerate(p.read_text(errors='replace').splitlines(), 1) if 'Method not decompiled:' in line]
    if hits: rows.append(f'- `{p.relative_to(ROOT)}`: {", ".join(hits)}')
(ROOT / 'docs/ORIGINAL_INVENTORY.md').write_text('\n'.join(rows) + '\n')
print(f'Inventoried {len(java)} Java and {len(smali)} Smali files.')
